name: "Deploy to Staging"
run-name: Deploy Content and Metadata from ${{ github.ref_name }} to Staging

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy content
        env:
          PENGUINCTL_APIURL: ${{ secrets.PENGUINCTL_APIURL_STAGING }}
          PENGUINCTL_APITOKEN: ${{ secrets.PENGUINCTL_APITOKEN_STAGING }}
        run: |
          make deploy
